name: tests

on:
    - push
    - pull_request

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['12', '14', '16', '17']
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-
            - uses: pnpm/action-setup@v2.1.0
              with:
                  version: 6.32.7
                  run_install: true
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - run: pnpm test
